name: New Integration

on: 
  workflow_dispatch:

jobs:
    Deploy-and-integrate:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: Logging to Azure
          uses: Azure/login@v1.6.1
          with:
             creds: ${{secrets.newsecret}}

        - name: retrieve all resource groups
          run: az group list

