name: Only Resource Group

on: 
  workflow_dispatch:
jobs:
   build:
      runs-on: ubuntu-latest

      steps:       
       - uses: actions/checkout@v3

       - uses: Azure/login@v1.6.1
         with:
             client-id: ${{secrets.CLIENT_ID}}
             tenant-id: ${{secrets.TENANT_ID}}
             subscription-id: ${{secrets.SUBSCIPTION_ID}}

       - run: az account list
