# This is a basic workflow to help you get started with Actions

name: Deploy storage account

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: Azure/login@v1.6.1
        with:
          creds: ${{ secrets.baha }}
<<<<<<< HEAD
      
  
      - run: |
         az group list
         az deployment group -n Server-RG --template-file './firstapp/azure-resources/storageaccounts.bicep'
=======

      - run: az group list

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        with:
            subscriptionId: 0c92d9fb-c043-40a4-b483-675cc3e84e07
            resourceGroupName: Server-RG
            template: ./firstapp/azure-resources/storageaccounts.bicep
          
>>>>>>> 33b814ffe6e3eb957ad2e84c30471ebd13351ab0
