name: deploying NETWORK

on: 
  workflow_dispatch:
jobs:
    build:
      runs-on: ubuntu-latest

      steps:       
       -  uses: actions/checkout@v3

       - uses: Azure/login@v1.6.1
         with:
             client-id: ${{secrets.CLIENT_ID}}
             tenant-id: ${{secrets.TENANT_ID}}
             subscription-id: ${{secrets.SUBSCRIPTION_ID}}

       - run: az group list

       - name: Deploy Storage account
         uses: Azure/arm-deploy@v1 
         with:
           subscriptionId: 0c92d9fb-c043-40a4-b483-675cc3e84e07
           resourceGroupName: RedooONE-rg
           template: ./firstapp/azure-resources/network.bicep
